### ISSUE TITLE
*command-line-args* not properly set, script path included with no option (or -p)

### ISSUE THREAD

**Issue by genovese** [kumarshantanu/lein-exec#19]
Thanks for a very useful plugin.

When invoked as   `lein exec foo.clj arg1 arg2...`, `*command-line-args*`
includes the script path (`foo.clj` in this case).  You can see this
on page 120 of exec.clj

```clojure
 (not option) (eval-script nil (first params) (pr-str params))
```
and similarly in the condition on line 118 (under the -p option).
The script path is kept in the params passed as arguments and
later bound to `*command-line-args*`. 

I think it should be  `(pr-str (rest params))` in that third argument.

**Comment by kumarshantanu** [comment]
That is by design. The script path is included in` *command-line-args*` as the first argument (like `$0` in _bash_) so that, should you need to print a help string to the user you can access the script name too.

Feel free to reopen if you spotted any bug in this respect.

**Comment by genovese** [comment]
Of course, silly of me.  Thanks.
