### ISSUE TITLE
Scripts won't run when cwd contains spaces

### ISSUE THREAD

**Issue by pmonks** [kumarshantanu/lein-exec#24]
The current lein-exec script doesn't function correctly when the current working directory contains spaces.  Further testing is needed, but what fixed it for me (Mac OS X) was:
```shell
#!/bin/bash

if [[ $1 =~ ^[~\/] ]]
then
  # its already an absolute path
  lein exec "$@"
else
  # This is a relative path, so make it absolute,
  # using the current directory as the base.
  lein exec "`pwd`/$@"
fi
```
(note where the starting double quote character is on line 10)

**Comment by kumarshantanu** [comment]
Tested this on Mac OS X (Yosemite) and Linux (Ubuntu 15.10). Thanks for the report and the suggested fix!

**Comment by pmonks** [comment]
No thank *you* for the great tool and the rapid turnaround!
